# xclim-timber Zarr Configuration Template
# Copy this file and customize for your dataset

# Data paths
data:
  input_path: /path/to/your/zarr/stores  # Path to Zarr data
  output_path: ./outputs
  log_path: ./logs

  # Zarr store patterns for each variable type
  # Modify these patterns to match your data organization
  zarr_stores:
    temperature:
      - '*temperature*.zarr'
      - '*tas*.zarr'
    precipitation:
      - '*precipitation*.zarr'
      - '*pr*.zarr'

# Processing settings
processing:
  temperature_units: degC  # Target units: degC or K

  # Chunk sizes for memory management
  chunk_size:
    time: 365  # Days to process at once
    lat: 100   # Spatial chunking
    lon: 100

  # Zarr optimizations
  zarr:
    consolidated: true  # Use consolidated metadata
    parallel_reads: true

# Climate indices to calculate
# Comment out any indices you don't need
indices:
  # Baseline period for percentile calculations
  baseline_period:
    start: 1991
    end: 2020

  # Temperature indices (requires temperature data)
  temperature:
    - tg_mean           # Annual mean temperature
    - frost_days        # Days with tmin < 0°C
    - summer_days       # Days with tmax > 25°C
    - growing_degree_days

  # Precipitation indices (requires precipitation data)
  precipitation:
    - prcptot          # Total precipitation
    - rx1day           # Max 1-day precipitation
    - cdd              # Consecutive dry days
    - r10mm            # Heavy precipitation days

# Output settings
output:
  format: netcdf  # Output format: netcdf or geotiff
  compression:
    complevel: 4
    engine: h5netcdf